/*/var xpos = camera_get_view_x(view_camera[0])/(room_width-(camera_get_view_width(view_camera[0])));
var ypos = camera_get_view_y(view_camera[0])/(room_height-(camera_get_view_height(view_camera[0])));

layer_background_xscale(layer_background_get_id("SkyBackgroundLayer1"), 0.75)
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer1"), 0.75)
layer_x("SkyBackgroundLayer1", camera_get_view_x(view_camera[0]))
layer_y("SkyBackgroundLayer1", camera_get_view_y(view_camera[0]))
layer_background_xscale(layer_background_get_id("SkyBackgroundLayer2"), 0.75)
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer2"), 0.75)
layer_x("SkyBackgroundLayer2", camera_get_view_x(view_camera[0]))
layer_y("SkyBackgroundLayer2", camera_get_view_y(view_camera[0]) - 32)

layer_background_xscale(layer_background_get_id("SkyBackgroundLayer3"), 0.75)
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer3"), 0.75)
layer_x("SkyBackgroundLayer3", camera_get_view_x(view_camera[0]))
layer_y("SkyBackgroundLayer3", camera_get_view_y(view_camera[0]) - 96)
layer_background_xscale(layer_background_get_id("SkyBackgroundLayer4"), 0.75)
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer4"), 0.75)
layer_x("SkyBackgroundLayer4", camera_get_view_x(view_camera[0]))
layer_y("SkyBackgroundLayer4", camera_get_view_y(view_camera[0]) - 160)
layer_background_xscale(layer_background_get_id("SkyBackgroundLayer5"), camera_get_view_width(view_camera[0]))
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer5"), camera_get_view_height(view_camera[0]))
//layer_x("SkyBackgroundLayer5", camera_get_view_x(0))
//layer_y("SkyBackgroundLayer5", camera_get_view_y(0))
layer_background_xscale(layer_background_get_id("SkyBackgroundLayer6"), camera_get_view_width(view_camera[0]))
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer6"), camera_get_view_height(view_camera[0]))
//layer_x("SkyBackgroundLayer6", camera_get_view_x(0))
//layer_y("SkyBackgroundLayer6", camera_get_view_y(0))
layer_background_xscale(layer_background_get_id("SkyBackgroundLayer7"), camera_get_view_width(view_camera[0]))
layer_background_yscale(layer_background_get_id("SkyBackgroundLayer7"), camera_get_view_height(view_camera[0]))
//layer_x("SkyBackgroundLayer7", camera_get_view_x(0))
//layer_y("SkyBackgroundLayer7", camera_get_view_y(0))/*/