var layerBackgroundId = layer_get_id("PBackground")
//var layerBackgroundIdRed = layer_get_id("PBackgroundRed")
//var layerBackgroundIdGreen = layer_get_id("PBackgroundGreen")
//var layerBackgroundIdBlue = layer_get_id("PBackgroundBlue")

//layer_vspeed(layerBackgroundIdRed, 0.125)
//layer_hspeed(layerBackgroundIdRed, 0.125)
//layer_vspeed(layerBackgroundIdGreen, -0.125)
//layer_hspeed(layerBackgroundIdGreen, 0)
//layer_vspeed(layerBackgroundIdBlue, 0.125)
//layer_hspeed(layerBackgroundIdBlue, -0.125)
layer_vspeed(layerBackgroundId, 0.0625)
layer_hspeed(layerBackgroundId, 0.0625)